language: generic
sudo: required
services:
- docker
before_install:
- docker build -t elzilch0/docker_react -f Dockerfile.dev .
script:
- docker run -e CI=true elzilch0/docker_react npm run test
deploy:
  edge: true
  provider: elasticbeanstalk
  access_key_id:
    secure: H3ELR+NaxSSBKQ/XrlO//EWopNWX+7PyTpfegMkRwFg8qgqOUJTicu42G3/Du3v799ug75hZ2/AhfrintNm9mrUPA/LOVLW6znDKu2rnumBHUq07j4SHV8vwlwWI09xW1HnfBiwM25fNs4LFNnv31sbCJMdaxAOaYlhSjqkWycwHFa3QnSPD/WnboSfqqcq0/o70LCuPJaF67jkja0Ynkqu6dwyZop9Fq9nzP0e5ExBplNhcVeqga6S+gA9RZryfBKxI4BshykQ+hbLNUbin0zunkWZL/nU8/dAdxUi2sYLYwKN5AZs1r1kgDFxQ2bxI5dy7TioC2/E7Qdi/ZUV641vLeiPxtq1zqd9RS+RfCD0SxhXddzXVSX16QPex42lf7Zhjj6UUH12ER33ezJkJDB+5mQP0y1DjIg+83B1pVZ1s/bHxdpC4HapR5DICRf6Bpq9WfOSBfAWO91bBMKRmSyo7D0O/BezGKD/dR/NsJ0xnsnEdP9TXNmh8iT96DHOikGxymOuTr43F3fIemKYI9Go1ut8qrrUjy8VjdiCWSEbyJN5TvoCr6RWVNLn+1N0XuLRPc4ZODlGYsP/V7Nht5v/ICmwNJiMWItBr4RldfWaKCU4fCkJ/s040CiQrNEzBGF/0dHKbwwYZhQZRM36alyvDO80qpNYyme3m/yvtNMs=
  secret_access_key:
    secure: VweJ9d5vGbkNhqitgdYWiFoAKb9EeKVq8IVStrlY+AJvcTOr84DIneqTI0DxlgV7OtPxBxVsThHDA8wnpT+hJfsdWrGfa6gr+Ud8lTBTfmp1/5o/Hkpd98tqlv5wk/UUPomAGCvb6Gc12nph9hWd9sFNksBHWkYW2BzhCEfHz9MqHHyKltCLbxZgFlVKx/5YTyN2mL5jlOBxHDRj0YK5ziQN6Du9X4MWL3RuzCxQco1ldnTWDgSsUcoO+8XJRutiOMZDRpDFyWsv5eZliEBlq7QGJ1gZy9uRerblcKGbNkcYdt8C/qdx2VAX0qhJYN8LfUitH5kwrSiqSIRLhLUwe3A0kDi7xyMiqq5PTlCPDnlEbfAMTJ0hLh00+Kv8ruy3LZhRXtFow2DkLSzvpWbdKgFw/0I5gUvGi0q1wmIsghcNVi/fuzdOCUFa+t43Sr7fRZCWaZCwXhn43Oc4jV6AlsdLuUOyy5k4EKcFukHxPQuLwr4KZIzt6/z0JKJqcd+Fidnd8QjbHTzwwkaTTEMYpV7TUG7OwWX4KIBxxxt3P9lfIUBq5UJ6DUQwkyUIPiTeMuFmlef6tv2TCOw/wEt9n77owxwGh0wjp5MsIaxb4dQLtGIwTfZSevtOBGaCsHUVI4tVSSUOKJULxXMd9CcQItLR3fL5NyTlOK2N3qnxsmY=
  region: us-east-1
  app: docker_react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-us-east-1-661933406886
  bucket_path: docker_react
  on:
    branch: master
