language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t elzilch0/docker_react -f Dockerfile.dev .

script:
  - docker run -e CI=true elzilch0/docker_react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker_react"
  environment: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-661933406886"
  bucket_path: "docker_react"
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
