language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t elzilch0/docker_react -f Dockerfile.dev .
script:
  - docker run -e CI=true elzilch0/docker_react npm run test
deploy:
  edge: true
  provider: elasticbeanstalk
  access_key_id: AKIAZUHSOHKTFKSQD7WZ
  secret_access_key:
    secure: VweJ9d5vGbkNhqitgdYWiFoAKb9EeKVq8IVStrlY+AJvcTOr84DIneqTI0DxlgV7OtPxBxVsThHDA8wnpT+hJfsdWrGfa6gr+Ud8lTBTfmp1/5o/Hkpd98tqlv5wk/UUPomAGCvb6Gc12nph9hWd9sFNksBHWkYW2BzhCEfHz9MqHHyKltCLbxZgFlVKx/5YTyN2mL5jlOBxHDRj0YK5ziQN6Du9X4MWL3RuzCxQco1ldnTWDgSsUcoO+8XJRutiOMZDRpDFyWsv5eZliEBlq7QGJ1gZy9uRerblcKGbNkcYdt8C/qdx2VAX0qhJYN8LfUitH5kwrSiqSIRLhLUwe3A0kDi7xyMiqq5PTlCPDnlEbfAMTJ0hLh00+Kv8ruy3LZhRXtFow2DkLSzvpWbdKgFw/0I5gUvGi0q1wmIsghcNVi/fuzdOCUFa+t43Sr7fRZCWaZCwXhn43Oc4jV6AlsdLuUOyy5k4EKcFukHxPQuLwr4KZIzt6/z0JKJqcd+Fidnd8QjbHTzwwkaTTEMYpV7TUG7OwWX4KIBxxxt3P9lfIUBq5UJ6DUQwkyUIPiTeMuFmlef6tv2TCOw/wEt9n77owxwGh0wjp5MsIaxb4dQLtGIwTfZSevtOBGaCsHUVI4tVSSUOKJULxXMd9CcQItLR3fL5NyTlOK2N3qnxsmY=
  region: us-east-1
  app: docker_react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-us-east-1-661933406886
  bucket_path: docker_react
  on:
    branch: master
